name: windows

on:
  push:
    paths-ignore:
    - '.github/workflows/**'
    - '!.github/workflows/windows.yml'
  pull_request:
    paths-ignore:
    - '.github/workflows/**'
    - '!.github/workflows/windows.yml'

env:
  CC: "cl"
  CXX: "cl"

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Meson and Ninja
      run: pip install meson ninja
    - name: Enter DevShell
      run: |
        function EnterDevShellEnv {
          $vsw = Get-Command 'vswhere'
          $VSFfavors = 'Community','Professional','Enterprise','BuildTools' | %{ "Microsoft.VisualStudio.Product.$_" }
          $vs = & $vsw.Path -products $VSFfavors -latest -format json | ConvertFrom-Json
          $tools_dir = Join-Path $vs.installationPath 'Common7' 'Tools'
          # Try the root tools dir
          $devshell = Join-Path $tools_dir 'Microsoft.VisualStudio.DevShell.dll'
          # Try finding it under vsdevshell
          if (!(Test-Path $devshell -Type Leaf)) {
              $devshell = Join-Path $tools_dir 'vsdevshell' 'Microsoft.VisualStudio.DevShell.dll'
          }
          # Fail if didn't find the DevShell library
          if (!(Test-Path $devshell -Type Leaf)) {
              throw "error: cannot find Microsoft.VisualStudio.DevShell.dll"
          }
          Import-Module $devshell
          Enter-VsDevShell -VsInstanceId $vs.instanceId -SkipAutomaticLocation -DevCmdArguments '-arch=${{ inputs.architecture }} -no_logo'
        }
        EnterDevShellEnv
    - name: Configure with meson for WIN32 backend only
      run: meson build -Ddisable_drm=true -Dwith_x11=no -Dwith_glx=no -Dwith_wayland=no -Dwith_win32=yes
    - name: Build and Install with ninja
      run: ninja -C build install